spring.application.name=project03
server.port=8080
spring.thymeleaf.prefix=file:./src/main/resources/templates/
spring.thymeleaf.cache=false
spring.web.resources.static-locations=file:./src/main/resources/static/,classpath:/static/
spring.web.resources.cache.period=0
spring.output.ansi.enabled=always
logging.pattern.console=%clr(%d{yyyy-MM-dd hh:mm:ss.SS}){faint} %clr([%level]) %clr(%logger.%M\\(\\)){magenta} : %msg%n%wEx
